services:
  agent:
    build: .
    container_name: agent
    tty: true
    stdin_open: true
    network_mode: "host"
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - KUBECONFIG=/kubeconfig
      - LLM_USER_PATH=/workspace/llm_config
    volumes:
      - ../cluster/kubeconfig/agent.yml:/kubeconfig
      - ../cluster/argocd/manifests:/manifests
      - ./:/workspace
      - ${SSH_AUTH_SOCK:-/tmp/ssh-agent}:/ssh-agent
